export const TOKEN_ISSUER = 'DAVIDADNW190_RESTAURANT_SRL';
export const TOKEN_AUDIENCE = 'DAVIDADNW190_AUDIENCE';
export const TOKEN_SIGN_ALGORITHM = 'ES512';
export const IS_PUBLIC_KEY = 'isPublic';
